# Generated by Django 3.0.7 on 2020-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
